-- local lib_names = {
-- 	Windows = {
-- 		x64 = "rust.dll",
-- 	},
-- 	OSX = {
-- 		arm64 = "librust_arm64.dylib",
-- 	},
-- 	Linux = {
-- 		-- x64 = "librust.so",
-- 	},
-- }
--
-- local function detect_lib_name()
-- 	local os_name = jit.os
-- 	local arch = jit.arch
--
-- 	local os_table = lib_names[os_name]
-- 	assert(os_table, "Unsupported OS: " .. tostring(os_name))
--
-- 	local lib_name = os_table[arch]
-- 	assert(lib_name, "Unsupported arch: " .. tostring(arch) .. " for OS: " .. tostring(os_name))
--
-- 	return lib_name
-- end
--
-- return detect_lib_name
